###

### A Python library is a collection of modules containing pre-written code that users can incorporate into their programs to perform specific tasks. It simplifies coding by providing reusable functions and classes, eliminating the need to write code from scratch. Libraries cover diverse domains, including data science, machine learning, web development, and more.


### Array is a linear data structure where all elements are arranged sequentially. It is a collection of elements of same data type stored at contiguous memory locations.


### Linear Data Structures are a type of data structure in computer science where data elements are arranged sequentially or linearly. Each element has a previous and next adjacent, except for the first and last elements.


In [2]:
import sys
num = 42
print(sys.getsizeof(num))  # Output: Memory size of integer 42
print(id(num))  # Output: Memory address of the integer object


num_float = 3.14
print(sys.getsizeof(num_float))  # Output: Memory size of float 3.14  
print(id(num_float))  # Output: Memory address of the float object

str_1 = "Yashi"
sys.getsizeof(str_1)

28
140717220908760
24
2149673281200


46

#### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.


In [3]:
!pip install numpy

In [4]:
lst_1 = [1,2,3,4]
print(lst_1)

[1, 2, 3, 4]


In [7]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,
               2,
               3,
               4,
               5])
print(arr1)
print(type(arr1))
print(arr1.shape)


arr2 = np.array([1.5,
                  2.5,
                  3.5,
                  4.5,
                  5.5])
print(arr2)
print(arr2.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[1.5 2.5 3.5 4.5 5.5]
(5,)


In [8]:
arr_1 = np.array(2)
print(arr_1.shape)
print(arr_1)

()
2


In [9]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

print(arr2)

[1 2 3 4 5]


In [10]:
arr2=np.array([[1,2,3,4,5]])
print(arr2.shape)
print(arr2)

(1, 5)
[[1 2 3 4 5]]


In [12]:
## 2d array
arr2=np.array([[1,2,3,4,5],
               [2,3,4,5,6],[10,11,12,13,15]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [10 11 12 13 15]]
(3, 5)


In [15]:
print(np.arange(0,10,2).reshape(5,1))

[[0]
 [2]
 [4]
 [6]
 [8]]


In [16]:
# np.arange(10,100,3).reshape(5,6)
np.arange(10,100,3).reshape(6,5)
# np.arange(10,100,3).reshape(10,3)
# np.arange(10,100,3).reshape(3,10)


array([[10, 13, 16, 19, 22],
       [25, 28, 31, 34, 37],
       [40, 43, 46, 49, 52],
       [55, 58, 61, 64, 67],
       [70, 73, 76, 79, 82],
       [85, 88, 91, 94, 97]])

In [18]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
## identity matrix
# np.eye(5)
print(np.eye(8))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [23]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [24]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [25]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [26]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [28]:
arr[0:1,2:]

array([[3, 4]])

In [ ]:
arr[0:,1:]

In [ ]:
arr

In [ ]:
print(arr[0][0])
print(arr[0][1])
print(arr[0][2])
print(arr[2][3])
print(arr[0:2,2:])

In [ ]:
arr[1:,2:]

In [ ]:
## Modify array elements
arr[0,0]=100
print(arr)

In [ ]:
arr[:]=100
print(arr)

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [ ]:
d

In [ ]:
print(d[0,0,0])

In [ ]:
d[1,0,0:]

In [ ]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
print(mean)
std_dev = np.std(data)
print(std_dev)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)
print(np.mean(normalized_data))
print(np.std(normalized_data))



In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

1. The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

2. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

3. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [ ]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
x = arr.view()
print(x)
arr[0] = 42

print(arr)
print(x)